# Generated by Django 5.1.7 on 2025-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='del_price',
            field=models.FloatField(null=True),
        ),
    ]
