# Generated by Django 5.1.7 on 2025-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_medicine_del_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Review',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
