# Generated by Django 5.1.7 on 2025-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_medicine_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='SKU',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Tag',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
