# Generated by Django 5.1.7 on 2025-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_medicine_sku_medicine_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
