# Generated by Django 5.1.7 on 2025-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_medicine_sku_alter_medicine_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('Review', models.CharField(max_length=8, null=True)),
                ('At', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
