# Generated by Django 5.1.7 on 2025-03-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review',
            new_name='review',
        ),
    ]
