# Generated by Django 5.1.7 on 2025-03-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_review_review_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
