# Generated by Django 5.1.7 on 2025-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Dental Care', 'Dental Care'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Medicine', 'Medicine')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(choices=[('Cardiologists', 'Cardiologists'), ('Dermatologists', 'Dermatologists'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Allergists', 'Allergists'), ('Immunologists', 'Immunologists')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Dr. James Adult', 'Dr. James Adult'), ('Dr. James Alison', 'Dr. James Alison'), ('Dr. Peter Adlock', 'Dr. Peter Adlock'), ('Dr. Jelin Alis', 'Dr. Jelin Alis'), ('Dr. Josh Taylor', 'Dr. Josh Taylor'), ('Dr. Steven Smith', 'Dr. Steven Smith')], max_length=50, null=True),
        ),
    ]
