# Generated by Django 5.1.7 on 2025-03-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_appointment_user_appointment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
    ]
