# Generated by Django 5.1.7 on 2025-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='Review',
        ),
    ]
