# Generated by Django 5.1.7 on 2025-03-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_remove_medicine_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='SKU',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Tag',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
