# Generated by Django 5.1.7 on 2025-03-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(null=True, upload_to='services'),
        ),
    ]
