# Generated by Django 5.1.6 on 2025-03-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialist', models.CharField(max_length=20)),
                ('img', models.ImageField(null=True, upload_to='doctors')),
            ],
        ),
    ]
