# Generated by Django 5.1.6 on 2025-03-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certifications',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practicearea',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
