# Generated by Django 5.1.6 on 2025-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_doctor_certifications_doctor_department_doctor_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(max_length=70),
        ),
    ]
