# Generated by Django 5.1.6 on 2025-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_doctor_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certifications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='practicearea',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
