# Generated by Django 5.1.7 on 2025-03-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
