# Generated by Django 5.1.7 on 2025-03-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.department'),
        ),
    ]
