# Generated by Django 5.1.7 on 2025-03-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_doctor_name_alter_doctor_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(max_length=70),
        ),
    ]
