# Generated by Django 5.1.7 on 2025-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_department_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='img',
            field=models.ImageField(null=True, upload_to='department'),
        ),
    ]
