# Generated by Django 5.1.6 on 2025-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_inquiry_city_inquiry_landmark_inquiry_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
