# Generated by Django 5.1.7 on 2025-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
