# Generated by Django 5.1.7 on 2025-04-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_inquiry_date_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='date_submitted',
        ),
    ]
