# Generated by Django 5.1.7 on 2025-04-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='specialist',
        ),
    ]
