# Generated by Django 5.1.7 on 2025-04-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_appointment_specialist_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='specialist',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='App.doctor'),
        ),
    ]
