# Generated by Django 5.1.7 on 2025-04-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineimage',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='EmailConfirmationLog',
        ),
        migrations.DeleteModel(
            name='MedicineImage',
        ),
    ]
